### ISSUE TITLE
ExpressionNode subclasses need to have ParameterInfo annotations

### ISSUE THREAD

**Issue by alexeid** [alexeid/linguaPhylo#42]
Currently a script like this will parse initially.

a ~ Exp(rate=1.0);
b ~ Exp(rate=a+1.0);

But it can't be sampled again because the ExpressionNode that defines a+1.0 does not have ParameterInfo, so the sample code can't a matching constructor to traverse the model correctly with new data. 

ExpressionNode either has to have ParameterInfo annotations added, or Sampler.java has to be made expression/parser aware, so that expressions that depend on random variables can be recalculated when the model is sampled.

**Comment by rbouckaert** [comment]
This is going to be tricky: `ExpressionNode` has a variable number of inputs, which can be obtained through `ExpressionNode.getInputs()`. If the expression is `a=b+c` it will have two inputs `b` and `c`, but with `a=b+c*d` it will have three inputs -- internally, it will contain two `ElementWise` objects, one for the + and one for the *, but those will not be exposed externally.

I added `ParameterInfo` annotations to `ExpressionNode2Args` and `ExpressionNode1Arg`, but not sure that this solves the problem.

**Comment by alexeid** [comment]
Uh oh. I am just looking at it now...

**Comment by alexeid** [comment]
So ParameterInfo annotations should only be for those parameters that are also nodes in the GraphicalModel. I don't think that the first two arguments of the constructor should be. The last one is a Varargs. This is going to be interesting :) I will keep playing.

**Comment by alexeid** [comment]
If ExpressionNode is going to conform to the pattern, then it shouldn't accept ExpressionNodes as children in the constructor, but only Values that are referenced by the Expression. They in turn, may be the result of ExpressionNodes. So consider the following code:

b ~ Exp(rate=1.0);
c ~ Exp(rate=1.0);
d ~ Exp(rate=1.0);

a = b + c * d;

Ideally this would result in DeterministicFunction object with fields:

String expression = "b + c * d";

And ParameterInfo annotated arguments of type Value with id's b, c and d.

When setParam("b", b) was called on that DeterministicFunction it would know what to do with it. Slot it in to the left argument of the + sub-expression.

**Comment by rbouckaert** [comment]
Glad this is fixed :-)

**Comment by alexeid** [comment]
Could review ExpressionNodeWrapper class? Currently I run REPL first and then call LPhyParser.Utils.wrapExpressionNodes(repl) afterwards in the GUI code. I suppose we could just make this call inside the REPL parse method instead to encapsulate it more. A lot of this parsing and sampling machinery seems a bit heavyweight at the moment. Perhaps some sort of refactoring of the core classes could make it nicer. I feel like there are a lot of instanceof and casting going on which isn't much fun.

**Comment by rbouckaert** [comment]
`ExpressionNode`s are currently producing `Value`s. Sub-expressions are producing `Value`s as well, which perhaps explains the overly enthousiastic use of casting between `DoubleValue`, `DoubleArrayValue` etc. and `Double`, `Double[]` etc. everywhere. So d=a+b*c parses are d=a+(b*c) and the b*c becomes a function that gets values of b and d from `Value` object, gets the Double values, calculates a new Double value, then puts the result in a new `Value` object, before going through the same process for the + bit of the expression. Internally, this is not necessary for an `Expression`, so there is certainly room to refactor it out of there. But I wonder whether this is worth the effort: is efficiency an issue for a simulator?

`ExpressionNodeWrapper` seems OK at first sight. If there were a unified way for deterministic and stochastic nodes to produce `Value`s quite a bit of that code might not be necessary -- in particular if a `sample()` was added to every graphical node (including constants and deterministic functions), that could make things much easier.

I don't see any issues having it called from REPL instead of `LPhyParser.Utils.wrapExpressionNodes(repl)`.

**Comment by alexeid** [comment]
I am very happy for you to fork and give this refactor a go! I think it would be nice for the expressions to be as efficient as possible. I just wanted to get a reference working, but I already found in other places that little inefficiencies mounted up when you want to generate 1000 samples.

**Comment by alexeid** [comment]
Maybe instead of `sample()` we should have `generate()`, in Parameterized, since that implies both stochastic and deterministic generation of values? But that still give two types of nodes: GenerativeNodes and GeneratedNodes.
